// <auto-generated />
using System;
using ErpKernmodul;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpKernmodul.Migrations
{
    [DbContext(typeof(ErpKontext))]
    [Migration("20260904154540_BestellungTabelleHinzugefuegt")]
    partial class BestellungTabelleHinzugefuegt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErpKernmodul.Bestellung", b =>
                {
                    b.Property<int>("BestellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BestellId"));

                    b.Property<DateTime>("Bestelldatum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Gesamtbetrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Lieferadresse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("kundenId")
                        .HasColumnType("int");

                    b.HasKey("BestellId");

                    b.HasIndex("kundenId");

                    b.ToTable("Bestellungen");
                });

            modelBuilder.Entity("ErpKernmodul.Kunde", b =>
                {
                    b.Property<int>("KundenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundenId"));

                    b.Property<string>("Ansprechpartner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Erfassunsdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firmenname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KundenNummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KundenId");

                    b.ToTable("Kunden");
                });

            modelBuilder.Entity("ErpKernmodul.Bestellung", b =>
                {
                    b.HasOne("ErpKernmodul.Kunde", "BestellenderKunde")
                        .WithMany("Bestellungen")
                        .HasForeignKey("kundenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BestellenderKunde");
                });

            modelBuilder.Entity("ErpKernmodul.Kunde", b =>
                {
                    b.Navigation("Bestellungen");
                });
#pragma warning restore 612, 618
        }
    }
}
